# Generated by Django 4.1 on 2022-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Customer_Category", models.CharField(max_length=65)),
                ("Entity_Type", models.CharField(max_length=3)),
                ("High", models.CharField(max_length=4)),
                ("Medium", models.CharField(max_length=6)),
                ("Low", models.CharField(max_length=3)),
                ("Score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Juridictional_Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Country_Juridiction", models.CharField(max_length=21)),
                ("High_Risk", models.CharField(max_length=22)),
                ("Medium", models.CharField(max_length=6)),
                ("Low", models.CharField(max_length=3)),
                ("Score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="List_Matching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("List_Name", models.CharField(max_length=62)),
                ("Very_High", models.IntegerField()),
                ("High", models.IntegerField()),
                ("Medium", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Product_Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Product", models.CharField(max_length=48)),
                ("High", models.CharField(max_length=4)),
                ("Medium", models.CharField(max_length=6)),
                ("Low", models.CharField(max_length=3)),
                ("Score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile_linkage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Parameters", models.CharField(max_length=134)),
                ("High", models.CharField(max_length=4)),
                ("Medium", models.CharField(max_length=6)),
                ("Low", models.CharField(max_length=3)),
                ("Score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction_Behavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Transaction", models.CharField(max_length=212)),
                ("Frquency_one", models.IntegerField()),
                ("Frquency_Two", models.IntegerField()),
                ("Frquency_Three", models.IntegerField()),
                ("Score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Weight_distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Filter_Number", models.IntegerField()),
                ("Risk_Assesment", models.CharField(max_length=35)),
                ("Description", models.CharField(max_length=250)),
                ("Weight", models.IntegerField()),
                ("Assesment_Score", models.IntegerField()),
            ],
        ),
    ]
