# Generated by Django 4.1 on 2022-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Transaction_Behavior",),
        migrations.AlterField(
            model_name="customer_type",
            name="High",
            field=models.CharField(default="NA", max_length=4),
        ),
        migrations.AlterField(
            model_name="customer_type",
            name="Low",
            field=models.CharField(default="NA", max_length=4),
        ),
        migrations.AlterField(
            model_name="customer_type",
            name="Medium",
            field=models.CharField(default="NA", max_length=6),
        ),
        migrations.AlterField(
            model_name="juridictional_risk",
            name="High_Risk",
            field=models.CharField(default="NA", max_length=22),
        ),
        migrations.AlterField(
            model_name="juridictional_risk",
            name="Low",
            field=models.CharField(default="NA", max_length=4),
        ),
        migrations.AlterField(
            model_name="juridictional_risk",
            name="Medium",
            field=models.CharField(default="Y", max_length=6),
        ),
        migrations.AlterField(
            model_name="product_service",
            name="High",
            field=models.CharField(default="NA", max_length=4),
        ),
        migrations.AlterField(
            model_name="product_service",
            name="Low",
            field=models.CharField(default="NA", max_length=4),
        ),
        migrations.AlterField(
            model_name="product_service",
            name="Medium",
            field=models.CharField(default="NA", max_length=6),
        ),
        migrations.AlterField(
            model_name="profile_linkage",
            name="Low",
            field=models.CharField(max_length=4),
        ),
    ]
