# Generated by Django 4.1 on 2022-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screens",
            "0002_delete_transaction_behavior_alter_customer_type_high_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction_Behavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Transaction", models.CharField(max_length=212)),
                ("Frquency_one", models.IntegerField()),
                ("Score_one", models.IntegerField()),
                ("Frquency_Two", models.IntegerField()),
                ("Score_two", models.IntegerField()),
                ("Frquency_Three", models.IntegerField()),
                ("Score_three", models.IntegerField()),
            ],
        ),
    ]
