# Generated by Django 4.0.4 on 2022-11-09 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_alter_transaction_behavior_frquency_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_behavior',
            name='default',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
