# Generated by Django 4.0.4 on 2022-11-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_transaction_behavior_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_behavior',
            name='default',
        ),
    ]
