# Generated by Django 4.0.4 on 2022-11-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0006_remove_transaction_behavior_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_behavior',
            name='Non_selected',
            field=models.CharField(default='None', max_length=4),
        ),
    ]
